services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    image: prompt-booster-frontend:v1.0
    container_name: prompt-booster-ui
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./docker/nginx.conf:/etc/nginx/http.d/default.conf